version: "3.8"

services:
  consent-manager:
    container_name: "consent-manager"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: consent-manager:latest
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongodb
    env_file:
      - .env
    networks:
      - consent-manager
      - ptx

  mongodb:
    container_name: "consent-manager-mongodb"
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    #    Uncomment to connect mongodb container to mongo compass or another service
    #    ports:
    #      - "27017:27017"
    volumes:
      - consent_data:/data/db
    networks:
      - consent-manager

networks:
  consent-manager:
    name: consent-manager
    driver: bridge
  ptx:
    name: ptx
    external: true

volumes:
  consent_data:
