apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: consent-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: { { .Values.mongodb.volume.storage } }
